### ISSUE TITLE
https://deisbuildartifacts.blob.core.windows.net/shellcheck/shellcheck-${SHELLCHECK_VERSION}-linux-amd64 is gone.

### ISSUE THREAD

**Issue by andyliuliming** [deis/docker-shell-dev#14]

**Comment by norshtein** [comment]
Have you ever substituted `${SHELLCHECK_VERSION}` with `v0.4.6`, and try `https://deisbuildartifacts.blob.core.windows.net/shellcheck/shellcheck-v0.4.6-linux-amd64`?

See [here](https://github.com/deis/docker-shell-dev/blob/master/Dockerfile#L4).

**Comment by andyliuliming** [comment]
hmmm.seems it's recovered...
I indeed use the substituted one...
